In [12]:
import pandas as pd 
import numpy as np 
import pickle 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, r2_score

In [13]:
data = pd.read_csv("Exam_Score_Prediction.csv")
data.head()

   student_id  age  gender  ... facility_rating  exam_difficulty  exam_score
0           1   17    male  ...             low             hard        58.9
1           2   23   other  ...          medium         moderate        54.8
2           3   22    male  ...            high         moderate        90.3
3           4   20   other  ...             low         moderate        29.7
4           5   20  female  ...             low         moderate        43.7

[5 rows x 13 columns]

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        20000 non-null  int64
 1   age               20000 non-null  int64
 2   gender            20000 non-null  object
 3   course            20000 non-null  object
 4   study_hours       20000 non-null  float64
 5   class_attendance  20000 non-null  float64
 6   internet_access   20000 non-null  object
 7   sleep_hours       20000 non-null  float64
 8   sleep_quality     20000 non-null  object
 9   study_method      20000 non-null  object
 10  facility_rating   20000 non-null  object
 11  exam_difficulty   20000 non-null  object
 12  exam_score        20000 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 2.0+ MB

In [15]:
if "student_id" in data.columns:
    data = data.drop(columns = ["student_id"])
data.head

<bound method NDFrame.head of        age  gender   course  ...  facility_rating  exam_difficulty exam_score
0       17    male  diploma  ...              low             hard       58.9
1       23   other      bca  ...           medium         moderate       54.8
2       22    male     b.sc  ...             high         moderate       90.3
3       20   other  diploma  ...              low         moderate       29.7
4       20  female  diploma  ...              low         moderate       43.7
...    ...     ...      ...  ...              ...              ...        ...
19995   18   other      bba  ...              low             easy       86.5
19996   18    male    b.com  ...           medium         moderate       60.9
19997   19   other  diploma  ...              low             easy       64.5
19998   19    male      bba  ...           medium         moderate       79.0
19999   20    male     b.sc  ...           medium         moderate       71.0

[20000 rows x 12 columns]>

In [16]:
label_encoders = {}

categorical_cols = data.select_dtypes(include="object").columns

for col in categorical_cols:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

data.head()

   age  gender  course  ...  facility_rating  exam_difficulty  exam_score
0   17       1       6  ...                1                1        58.9
1   23       2       5  ...                2                2        54.8
2   22       1       1  ...                0                2        90.3
3   20       2       6  ...                1                2        29.7
4   20       0       6  ...                1                2        43.7

[5 rows x 12 columns]

In [17]:
X = data.drop("exam_score", axis=1)
y = data["exam_score"]

print("Features:")
print(X.columns)

Features:
Index(['age', 'gender', 'course', 'study_hours', 'class_attendance',
       'internet_access', 'sleep_hours', 'sleep_quality', 'study_method',
       'facility_rating', 'exam_difficulty'],
      dtype='object')

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 16000
Testing samples: 4000

In [19]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Model trained successfully")

Model trained successfully

In [20]:
y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("R2 Score:", r2)

Mean Absolute Error: 8.80058375281766
R2 Score: 0.6674472231649904

In [23]:
pickle.dump(model, open("model/model.pkl", "wb"))
pickle.dump(label_encoders, open("model/encoders.pkl", "wb"))

print("Model saved in model folder")

Model saved in model folder

In [22]:
sample_data = X_test.iloc[0].values.reshape(1, -1)

prediction = model.predict(sample_data)

print("Predicted Score:", prediction[0])
print("Actual Score:", y_test.iloc[0])

Predicted Score: 35.98941727438205
Actual Score: 31.1

c:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(